os: Visual Studio 2015

environment:
  matrix:
    - channel: stable
      target: x86_64-pc-windows-msvc
    - channel: beta
      target: x86_64-pc-windows-msvc
    - channel: nightly
      target: x86_64-pc-windows-msvc
      EXTRA_FEATURES: unstable
    - channel: 1.20.0 # Oldest supported version. Keep in sync with README.md.
      target: x86_64-pc-windows-msvc

cache:
  - 'C:\Users\appveyor\.cargo'
  - target

matrix:
  allow_failures:
    - channel: nightly

install:
- appveyor-retry appveyor DownloadFile https://win.rustup.rs/ -FileName rustup-init.exe
- rustup-init.exe -y --default-host %target% --default-toolchain %channel%
- set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
- rustc -V
- cargo -V

build_script:
- cmd: cargo build --release --verbose --features="all %EXTRA_FEATURES%"

test_script:
- cmd: cargo test --all --release --verbose --features="all %EXTRA_FEATURES%"

branches:
  only:
    - master
    - /\d+\.\d+\.\d+/

before_deploy:
  - ps: |
        $NAME = "sccache-${env:APPVEYOR_REPO_TAG_NAME}-${env:TARGET}"
        New-Item -Path $NAME -ItemType directory
        Copy-Item target/release/sccache.exe "${NAME}/"
        Copy-Item LICENSE "${NAME}/"
        Copy-Item README.md "${NAME}/"
        7z a -ttar "${NAME}.tar" "${NAME}"
        7z a "${NAME}.tar.gz" "${NAME}.tar"
        Push-AppveyorArtifact "${NAME}.tar.gz"

deploy:
  artifact: /.*\.tar.gz/
  auth_token:
    secure: W0QWCXm6EgiwSZ43z64VZdxZSHNsZwaulEthPjcn6L4lBcA4JSCkpsjAMA9o9agD
  description: ''
  on:
    appveyor_repo_tag: true
  provider: GitHub
  force_update: true
