name: Benchmarks

# spell-checker:ignore codspeed dtolnay Swatinem

on:
  pull_request:
  push:
    branches:
      - '*'

permissions:
  contents: read # to fetch code (actions/checkout)

# End the current execution if there is a new changeset in the PR.
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  benchmarks:
    name: Run performance benchmarks (CodSpeed)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-codspeed
        shell: bash
        run: cargo install cargo-codspeed --locked

      - name: Build benchmarks
        shell: bash
        run: cargo codspeed build

      - name: Run performance benchmarks
        uses: CodSpeedHQ/action@v4
        env:
          CODSPEED_LOG: debug
        with:
          mode: simulation
          run: cargo codspeed run > /dev/null
          token: ${{ secrets.CODSPEED_TOKEN }}

  memory-benchmarks:
    name: Run memory benchmarks (CodSpeed)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: dtolnay/rust-toolchain@stable

      - uses: Swatinem/rust-cache@v2

      - name: Install cargo-codspeed
        shell: bash
        run: cargo install cargo-codspeed --locked

      - name: Build benchmarks for memory analysis
        shell: bash
        run: cargo codspeed build -m analysis

      - name: Run memory benchmarks
        uses: CodSpeedHQ/action@v4
        env:
          CODSPEED_LOG: debug
        with:
          mode: memory
          run: cargo codspeed run > /dev/null
          token: ${{ secrets.CODSPEED_TOKEN }}
